name: CI
on:
  pull_request:
  push:
    branches: [ master, dev ]
  schedule: [ cron: "0 6 * * 4" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Get Cargo version
        id: cargo_version
        run: echo "::set-output name=version::$(cargo -V | tr -d ' ')"
        shell: bash

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.cargo_version.outputs.version }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: ${{ runner.os }}-${{ steps.cargo_version.outputs.version }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --features=serde --verbose

  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  check_documentation:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: documentation

      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo +nightly doc --no-deps --document-private-items
