name: Pull Request Check

on:
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
            ./target
            ~/.cargo
        key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
        restore-keys: ${{ runner.os }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
